"""new channel handling

Revision ID: 424d201adbb9
Revises: 716757a187a7
Create Date: 2025-07-27 02:01:10.445032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424d201adbb9'
down_revision: Union[str, None] = '716757a187a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joined_channels',
    sa.Column('user_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.drop_table('channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('channels_pkey'))
    )
    op.drop_table('joined_channels')
    # ### end Alembic commands ###
