"""pyramid stats

Revision ID: 61185473d5c2
Revises: 424d201adbb9
Create Date: 2025-07-31 17:40:09.198426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61185473d5c2'
down_revision: Union[str, None] = '424d201adbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acorn_pyramid_user',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('destroyer_name', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_acorn_pyramid_user_channel_name'), 'acorn_pyramid_user', ['channel_name'], unique=False)
    op.create_index(op.f('ix_acorn_pyramid_user_destroyer_name'), 'acorn_pyramid_user', ['destroyer_name'], unique=False)
    op.create_index(op.f('ix_acorn_pyramid_user_user_name'), 'acorn_pyramid_user', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acorn_pyramid_user_user_name'), table_name='acorn_pyramid_user')
    op.drop_index(op.f('ix_acorn_pyramid_user_destroyer_name'), table_name='acorn_pyramid_user')
    op.drop_index(op.f('ix_acorn_pyramid_user_channel_name'), table_name='acorn_pyramid_user')
    op.drop_table('acorn_pyramid_user')
    # ### end Alembic commands ###
