"""pyramid name for user data

Revision ID: 66cd66df3029
Revises: 61185473d5c2
Create Date: 2025-07-31 17:43:00.117276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cd66df3029'
down_revision: Union[str, None] = '61185473d5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acorn_pyramid_user', sa.Column('pyramid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acorn_pyramid_user', 'pyramid')
    # ### end Alembic commands ###
