"""Redid more stuff frfr

Revision ID: 716757a187a7
Revises: f8e0e1b41cd2
Create Date: 2025-07-27 00:25:59.250038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716757a187a7'
down_revision: Union[str, None] = 'f8e0e1b41cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acorn_pyramid_profile',
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('up', sa.Float(), nullable=False),
    sa.Column('upx', sa.Float(), nullable=False),
    sa.Column('down', sa.Float(), nullable=False),
    sa.Column('downx', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('profile_name')
    )
    op.drop_table('acorn_pyramid_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acorn_pyramid_profiles',
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('up', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('upx', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('down', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('downx', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_name', name=op.f('acorn_pyramid_profiles_pkey'))
    )
    op.drop_table('acorn_pyramid_profile')
    # ### end Alembic commands ###
