"""Active Channels

Revision ID: 863bf7d2fbfd
Revises: f9c0967dc0b7
Create Date: 2025-01-14 21:47:50.652414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '863bf7d2fbfd'
down_revision: Union[str, None] = 'f9c0967dc0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_active_channels',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('active_channels', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_active_channels')
    # ### end Alembic commands ###
