"""pyramid user fucked up nullable

Revision ID: b9b106e87ac3
Revises: 67cdf0b37074
Create Date: 2025-07-31 17:53:47.209788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b106e87ac3'
down_revision: Union[str, None] = '67cdf0b37074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acorn_pyramid_user', 'destroyer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acorn_pyramid_user', 'destroyer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
