"""channel settings

Revision ID: cef154af4e9f
Revises: b9b106e87ac3
Create Date: 2025-08-07 13:45:22.029932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cef154af4e9f'
down_revision: Union[str, None] = 'b9b106e87ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joined_channels', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('joined_channels', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('joined_channels', sa.Column('ambassators', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('joined_channels', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('joined_channels', 'settings')
    op.drop_column('joined_channels', 'ambassators')
    op.drop_column('joined_channels', 'active')
    op.drop_column('joined_channels', 'user_id')
    # ### end Alembic commands ###
