"""Redid some stuff fr

Revision ID: f8e0e1b41cd2
Revises: 1b09b4dc4ec6
Create Date: 2025-07-26 21:27:36.899378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8e0e1b41cd2'
down_revision: Union[str, None] = '1b09b4dc4ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acorn_pyramid_data',
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('facts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('acorn_pyramid_profiles',
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('up', sa.Float(), nullable=False),
    sa.Column('upx', sa.Float(), nullable=False),
    sa.Column('down', sa.Float(), nullable=False),
    sa.Column('downx', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acorn_pyramid_profiles')
    op.drop_table('acorn_pyramid_data')
    # ### end Alembic commands ###
